server {
    listen 80;
    server_name jeewanjyoti.org.np www.jeewanjyoti.org.np;

    root /root/jeewanjyoti_preorder-site/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}